# Generated by Django 2.0.6 on 2019-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechaAplicacionVac', models.DateField()),
                ('nombreProxVac', models.CharField(max_length=60)),
                ('fechaProxVac', models.DateField()),
                ('cantDosis', models.IntegerField()),
            ],
        ),
    ]
