# Generated by Django 2.0.6 on 2019-07-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registroMascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAplicacionVac', models.DateField()),
                ('nombreProxVac', models.CharField(max_length=60)),
                ('fechaProxVac', models.DateField()),
                ('cantDosis', models.IntegerField()),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='controlvacuna',
            name='vacu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlVacunas.Vacuna'),
        ),
    ]
