# Generated by Django 2.0.6 on 2019-06-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0003_auto_20190602_1943'),
        ('controlVacunas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAplicacionVac', models.DateField()),
                ('nombreProxVac', models.CharField(max_length=60)),
                ('fechaProxVac', models.DateField()),
                ('cantDosis', models.IntegerField()),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Expediente')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='cantDosis',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='fechaAplicacionVac',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='fechaProxVac',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='nombreProxVac',
        ),
        migrations.AddField(
            model_name='controlvacuna',
            name='vacu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlVacunas.Vacuna'),
        ),
    ]
