# Generated by Django 2.0.6 on 2019-06-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registroMascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDesparasitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAplicacion', models.DateField()),
                ('fechaProxDes', models.DateField()),
                ('dosisDesp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desparasitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDesparasitante', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='controldesparasitacion',
            name='desparasitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlDesp.Desparasitante'),
        ),
        migrations.AddField(
            model_name='controldesparasitacion',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Expediente'),
        ),
    ]
