# Generated by Django 2.0.6 on 2019-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('detalleConsulta', models.TextField()),
                ('medicamento', models.TextField()),
                ('proximaCita', models.DateField()),
                ('citaunica', models.BooleanField()),
            ],
        ),
    ]
