# Generated by Django 2.0.6 on 2019-06-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registroMascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('detalleConsulta', models.TextField()),
                ('medicamento', models.TextField()),
                ('proximaCita', models.DateField()),
                ('citaunica', models.BooleanField()),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Expediente')),
            ],
        ),
    ]
