# Generated by Django 2.0.6 on 2019-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dueñoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacDueno', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(max_length=8)),
                ('celular', models.IntegerField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('razaPadre', models.CharField(max_length=30)),
                ('razaMadre', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
                ('inicioControl', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
