# Generated by Django 2.0.6 on 2019-06-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueñoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('fechaNacDueno', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioControl', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('razaPadre', models.CharField(max_length=30)),
                ('razaMadre', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
                ('dueñomascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Mascota'),
        ),
    ]
