# Generated by Django 2.0.6 on 2019-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueñomascota',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dueñomascota',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
