# Generated by Django 2.0.6 on 2019-06-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0002_auto_20190602_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioControl', models.DateField(auto_now_add=True)),
                ('dueñomascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota')),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='inicioControl',
        ),
        migrations.AddField(
            model_name='expediente',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Mascota'),
        ),
    ]
