# Generated by Django 2.0.6 on 2019-06-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0012_auto_20190617_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dueñomascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota'),
        ),
    ]
