# Generated by Django 2.0.6 on 2019-06-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0014_auto_20190617_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueñomascota',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dueñomascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota'),
        ),
    ]
