# Generated by Django 2.0.6 on 2019-06-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0015_auto_20190622_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueñomascota',
            name='apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dueñomascota',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dueñomascota',
            name='fechaNacDueno',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dueñomascota',
            name='nombres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dueñomascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota'),
        ),
    ]
