# Generated by Django 2.0.6 on 2019-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0016_auto_20190622_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='dueñomascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueñomascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.DueñoMascota'),
        ),
    ]
