# Generated by Django 2.0.6 on 2019-06-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVacunaCelo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioCelo', models.DateField(unique=True)),
                ('fechaFinCelo', models.DateField(unique=True)),
                ('fechaAplic', models.DateField(unique=True)),
                ('celo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCelo.Celo')),
            ],
        ),
    ]
