# Generated by Django 2.0.6 on 2019-06-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlCelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioCelo', models.DateField()),
                ('fechaFinCelo', models.DateField()),
                ('fechaAplic', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='celo',
            old_name='nombreVacuna',
            new_name='nombreVacunaCelo',
        ),
        migrations.RemoveField(
            model_name='celo',
            name='fechaAplic',
        ),
        migrations.RemoveField(
            model_name='celo',
            name='fechaFinCelo',
        ),
        migrations.RemoveField(
            model_name='celo',
            name='fechaInicioCelo',
        ),
        migrations.AddField(
            model_name='controlcelo',
            name='celo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCelo.Celo'),
        ),
    ]
