# Generated by Django 2.0.6 on 2019-06-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascota', '0001_initial'),
        ('controlCelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcelo',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroMascota.Expediente'),
        ),
        migrations.AddField(
            model_name='controlcelo',
            name='proximoCelo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaAplic',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaFinCelo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaInicioCelo',
            field=models.DateField(),
        ),
    ]
