# Generated by Django 2.0.6 on 2019-06-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlCelo', '0004_auto_20190602_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcelo',
            name='celo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlCelo.Celo'),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaAplic',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaFinCelo',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='controlcelo',
            name='fechaInicioCelo',
            field=models.DateField(unique=True),
        ),
    ]
